version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shim
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shim-server
    environment:
      - PORT=${SERVER_PORT}
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env.development

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - '5050:80'
    depends_on:
      - db
